/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import javax.swing.JOptionPane;
import alcancia.HandlerFile;
import alcancia.JsonAlcancia;
/**
 *
 * @author JyK
 */
public class Vprincipal extends javax.swing.JFrame {

    /**
     * Creates new form Vprincipal
     */
    public Vprincipal(int contMoneda50, int contMoneda100, int contMoneda200, int contMoneda500, int contMoneda1000) {
      
        this.contMoneda50 = contMoneda50;        
        this.contMoneda100 = contMoneda100;
        this.contMoneda200 = contMoneda200;
        this.contMoneda500 = contMoneda500;
        this.contMoneda1000 = contMoneda1000;

        initComponents(); 
        
    }
      // contadores de moneda de cada denominacion
    private int contMoneda50 ;  
    private int contMoneda100 ; 
    private int contMoneda200 ; 
    private int contMoneda500 ; 
    private int contMoneda1000 ; 
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAñadir = new javax.swing.JButton();
        SpM50 = new javax.swing.JSpinner();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        SpM100 = new javax.swing.JSpinner();
        SpM200 = new javax.swing.JSpinner();
        SpM500 = new javax.swing.JSpinner();
        SpM1000 = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        btnCantM50 = new javax.swing.JButton();
        btnD50 = new javax.swing.JButton();
        ComboBox_Moneda = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AlcanciaAPP");
        setResizable(false);

        jLabel1.setText("Insertar Monedas");

        jLabel3.setText("Denominacion :");

        btnAñadir.setText("añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        SpM50.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(240, 240, 240));
        jTextField2.setText("50");

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(240, 240, 240));
        jTextField3.setText("100");

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(240, 240, 240));
        jTextField4.setText("200");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(240, 240, 240));
        jTextField5.setText("500");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(240, 240, 240));
        jTextField6.setText("1000");

        SpM100.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        SpM200.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        SpM500.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        SpM1000.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(btnAñadir)
                .addGap(93, 93, 93))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SpM1000, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(SpM500)
                            .addComponent(SpM200)
                            .addComponent(SpM100)
                            .addComponent(SpM50)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpM50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpM100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpM200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpM500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpM1000, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAñadir)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setText("Consultas de Monedas");

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(240, 240, 240));
        jTextField11.setText("Seleccione Moneda");

        btnCantM50.setText("Cantidad de Monedas");
        btnCantM50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantM50ActionPerformed(evt);
            }
        });

        btnD50.setText("Cantidad de Dinero");
        btnD50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD50ActionPerformed(evt);
            }
        });

        ComboBox_Moneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "50", "100", "200", "500", "1000", "Todas", " " }));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Vaciar alcancia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComboBox_Moneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCantM50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnD50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox_Moneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCantM50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnD50)
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        // Variables igualadas a los spinner para saber la cantidad que desea añadir  
        
        Integer cantañadir_50 = (Integer)SpM50.getValue(); 
        Integer cantañadir_100 = (Integer)SpM100.getValue(); 
        Integer cantañadir_200 = (Integer)SpM200.getValue(); 
        Integer cantañadir_500 = (Integer)SpM500.getValue(); 
        Integer cantañadir_1000 = (Integer)SpM1000.getValue();
        
         //condicionales para añadir a contador de cada valor de moneda
        if( cantañadir_50 > 0)
        {
        contMoneda50 = contMoneda50 + cantañadir_50 ;  
        
        }  
        
        if( cantañadir_100 > 0)
        {
        contMoneda100 = contMoneda100 + cantañadir_100 ;  
        
        } 
        
        if( cantañadir_200 > 0)
            contMoneda200 = contMoneda200 + cantañadir_200 ;  

        if( cantañadir_500 > 0)
            contMoneda500 = contMoneda500 + cantañadir_500 ;  

         if( cantañadir_1000 > 0)
            contMoneda1000 = contMoneda1000 + cantañadir_1000 ;  

        new HandlerFile().JsonUpdateFile(contMoneda50,contMoneda100,contMoneda200,contMoneda500,contMoneda1000);
         // se restauran los valores de los spinner al finalizar la operacion
        SpM50.setValue(0); 
        SpM100.setValue(0); 
        SpM200.setValue(0); 
        SpM500.setValue(0);
        SpM1000.setValue(0);
//fin
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnD50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD50ActionPerformed
        
    //Case para determinar cantidad de dinero por moneda
        switch ((String)ComboBox_Moneda.getSelectedItem()) {
            case "50" :
                    JOptionPane.showMessageDialog(this,"La cantidad de dinero en monedas de 50 es \n:" +(contMoneda50* 50) + "COP" ); 
                    break;
                    
            case "100" : 
                
               JOptionPane.showMessageDialog(this,"La cantidad de dinero en monedas de 100 es \n:" +(contMoneda100* 100) + "COP" ); 
                break; 
                
            case "200" : 
                JOptionPane.showMessageDialog(this,"La cantidad de dinero en monedas de 200 es \n:" +(contMoneda200* 200) + "COP" );
                break; 
                
            case "500" : 
                JOptionPane.showMessageDialog(this,"La cantidad de dinero en monedas de 500 es \n:" +(contMoneda500* 500) + "COP" );
                break; 
                
            case "1000" : 
                JOptionPane.showMessageDialog(this,"La cantidad de dinero en monedas de 1000 es \n:" +(contMoneda1000* 1000) + "COP" );
                break; 
                
            case "Todas" : 
                JOptionPane.showMessageDialog(this,"La cantidad  total de dinero en la alcancia es : \n"+ ((contMoneda500*500)+(contMoneda1000*1000)+(contMoneda200*200)+(contMoneda100*100)+(contMoneda50*50) ) +"COP" + "\n" +
                        "Detalles : \n" +  
                        "La cantidad de dinero en monedas de 50 es \n:" +(contMoneda50* 50) + "COP" +"\n" + 
                        "La cantidad de dinero en monedas de 100 es \n:" +(contMoneda100* 100) + "COP" +"\n" + 
                        "La cantidad de dinero en monedas de 200 es \n:" +(contMoneda200* 200) + "COP" +"\n" + 
                        "La cantidad de dinero en monedas de 500 es \n:" +(contMoneda500* 500) + "COP" +"\n" + 
                        "La cantidad de dinero en monedas de 1000 es \n:" +(contMoneda1000* 1000) + "COP" +"\n"  
                        
                        ); 
                break; 
                
            default : 
                JOptionPane.showMessageDialog(this,"Por favor Seleccione Denominacion de moneda a consultar " ); 
                break; 
                
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD50ActionPerformed

    private void btnCantM50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantM50ActionPerformed
        
        //switch para determinar la cantidad de cada una de las monedas
         String Valor = (String)ComboBox_Moneda.getSelectedItem(); //variable que define la denominacion
        
         switch (Valor) {
            case "50" :
                    JOptionPane.showMessageDialog(this, "La cantidad de monedas de 50 COP es : \n" +contMoneda50 ); 
                    break;
                    
            case "100" : 
                
                JOptionPane.showMessageDialog(this,"La cantidad de monedas de 100 COP es : \n"+ contMoneda100 ); 
                break; 
                
            case "200" : 
                JOptionPane.showMessageDialog(this,"La cantidad de monedas de 200 COP es : \n"+ contMoneda200 ); 
                break; 
                
            case "500" : 
                JOptionPane.showMessageDialog(this,"La cantidad de monedas de 500 COP es : \n"+ contMoneda500 ); 
                break; 
                
            case "1000" : 
                JOptionPane.showMessageDialog(this,"La cantidad de monedas de 1000 COP es : \n"+ contMoneda1000 ); 
                break; 
                
            case "Todas" : 
                JOptionPane.showMessageDialog(this,"La cantidad total de monedas en la alcancia es : "+ (contMoneda500+contMoneda1000+contMoneda200+contMoneda100+contMoneda50 ) + "\n" + 
                        "Detalles : \n"+
                "La cantidad de monedas de 50 es :" + contMoneda50 + "\n" + 
                "La cantidad de monedas de 100 es :" + contMoneda100 + "\n" + 
                "La cantidad de monedas de 200 es : \n"+ contMoneda200 +"\n"+ 
                 "La cantidad de monedas de 500 es : \n"+ contMoneda500 +"\n"+   
                "La cantidad de monedas de 1000 es : \n"+ contMoneda1000       ); 
                break; 
              //La siguiente opcion determina si no se ha seleccionado ninguna moneda  
            default : 
                JOptionPane.showMessageDialog(this,"Por favor Seleccione Denominacion de moneda a consultar " ); 
                break; 
                
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCantM50ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int resp = JOptionPane.showConfirmDialog(this, "¿Esta seguro?", "Alerta!", JOptionPane.YES_NO_OPTION);
        
    if(resp == JOptionPane.YES_OPTION) {
        new HandlerFile().JsonUpdateFile(0,0,0,0,0);
        RefreshData(); 
        JOptionPane.showMessageDialog (this, "Operacion Exitosa" , "Notificacion" , JOptionPane.INFORMATION_MESSAGE);
    }
        
                          
    }//GEN-LAST:event_jButton1ActionPerformed
    private void RefreshData(){
        this.contMoneda50 = 0;        
        this.contMoneda100 = 0;
        this.contMoneda200 = 0;
        this.contMoneda500 = 0;
        this.contMoneda1000 = 0;
    } 
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_Moneda;
    private javax.swing.JSpinner SpM100;
    private javax.swing.JSpinner SpM1000;
    private javax.swing.JSpinner SpM200;
    private javax.swing.JSpinner SpM50;
    private javax.swing.JSpinner SpM500;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnCantM50;
    private javax.swing.JButton btnD50;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
